// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: cart.proto

package server

import (
	"context"

	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/cart/rpc/cart"
	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/cart/rpc/internal/logic"
	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/cart/rpc/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) AddToCart(ctx context.Context, in *cart.AddToCartRequest) (*cart.AddToCartResponse, error) {
	l := logic.NewAddToCartLogic(ctx, s.svcCtx)
	return l.AddToCart(in)
}

func (s *CartServer) RemoveFromCart(ctx context.Context, in *cart.RemoveFromCartRequest) (*cart.RemoveFromCartResponse, error) {
	l := logic.NewRemoveFromCartLogic(ctx, s.svcCtx)
	return l.RemoveFromCart(in)
}

func (s *CartServer) ListCartItems(ctx context.Context, in *cart.ListCartItemsRequest) (*cart.ListCartItemsResponse, error) {
	l := logic.NewListCartItemsLogic(ctx, s.svcCtx)
	return l.ListCartItems(in)
}
