// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: reply.proto

package server

import (
	"context"

	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/reply/rpc/internal/logic"
	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/reply/rpc/internal/svc"
	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/reply/rpc/reply"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	reply.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) AddReply(ctx context.Context, in *reply.AddReplyRequest) (*reply.AddReplyResponse, error) {
	l := logic.NewAddReplyLogic(ctx, s.svcCtx)
	return l.AddReply(in)
}

func (s *ReplyServer) DeleteReply(ctx context.Context, in *reply.DeleteReplyRequest) (*reply.DeleteReplyResponse, error) {
	l := logic.NewDeleteReplyLogic(ctx, s.svcCtx)
	return l.DeleteReply(in)
}

func (s *ReplyServer) ListReplies(ctx context.Context, in *reply.ListRepliesRequest) (*reply.ListRepliesResponse, error) {
	l := logic.NewListRepliesLogic(ctx, s.svcCtx)
	return l.ListReplies(in)
}
