// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package userclient

import (
	"context"

	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserCollectionRequest          = user.AddUserCollectionRequest
	AddUserCollectionResponse         = user.AddUserCollectionResponse
	AddUserReceiveAddressRequest      = user.AddUserReceiveAddressRequest
	AddUserReceiveAddressResponse     = user.AddUserReceiveAddressResponse
	DeleteUserCollectionRequest       = user.DeleteUserCollectionRequest
	DeleteUserCollectionResponse      = user.DeleteUserCollectionResponse
	DeleteUserReceiveAddressRequest   = user.DeleteUserReceiveAddressRequest
	DeleteUserReceiveAddressResponse  = user.DeleteUserReceiveAddressResponse
	EditUserReceiveAddressRequest     = user.EditUserReceiveAddressRequest
	EditUserReceiveAddressResponse    = user.EditUserReceiveAddressResponse
	GetUserCollectionListRequest      = user.GetUserCollectionListRequest
	GetUserCollectionListResponse     = user.GetUserCollectionListResponse
	GetUserInfoRequest                = user.GetUserInfoRequest
	GetUserInfoResponse               = user.GetUserInfoResponse
	GetUserReceiveAddressInfoRequest  = user.GetUserReceiveAddressInfoRequest
	GetUserReceiveAddressListRequest  = user.GetUserReceiveAddressListRequest
	GetUserReceiveAddressListResponse = user.GetUserReceiveAddressListResponse
	LoginRequest                      = user.LoginRequest
	LoginResponse                     = user.LoginResponse
	UserInfo                          = user.UserInfo
	UserReceiveAddress                = user.UserReceiveAddress

	User interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		AddUserReceiveAddress(ctx context.Context, in *AddUserReceiveAddressRequest, opts ...grpc.CallOption) (*AddUserReceiveAddressResponse, error)
		EditUserReceiveAddress(ctx context.Context, in *EditUserReceiveAddressRequest, opts ...grpc.CallOption) (*EditUserReceiveAddressResponse, error)
		DeleteUserReceiveAddress(ctx context.Context, in *DeleteUserReceiveAddressRequest, opts ...grpc.CallOption) (*DeleteUserReceiveAddressResponse, error)
		GetUserReceiveAddressList(ctx context.Context, in *GetUserReceiveAddressListRequest, opts ...grpc.CallOption) (*GetUserReceiveAddressListResponse, error)
		AddUserCollection(ctx context.Context, in *AddUserCollectionRequest, opts ...grpc.CallOption) (*AddUserCollectionResponse, error)
		DeleteUserCollection(ctx context.Context, in *DeleteUserCollectionRequest, opts ...grpc.CallOption) (*DeleteUserCollectionResponse, error)
		GetUserCollectionList(ctx context.Context, in *GetUserCollectionListRequest, opts ...grpc.CallOption) (*GetUserCollectionListResponse, error)
		GetUserReceiveAddressInfo(ctx context.Context, in *GetUserReceiveAddressInfoRequest, opts ...grpc.CallOption) (*UserReceiveAddress, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) AddUserReceiveAddress(ctx context.Context, in *AddUserReceiveAddressRequest, opts ...grpc.CallOption) (*AddUserReceiveAddressResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddUserReceiveAddress(ctx, in, opts...)
}

func (m *defaultUser) EditUserReceiveAddress(ctx context.Context, in *EditUserReceiveAddressRequest, opts ...grpc.CallOption) (*EditUserReceiveAddressResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditUserReceiveAddress(ctx, in, opts...)
}

func (m *defaultUser) DeleteUserReceiveAddress(ctx context.Context, in *DeleteUserReceiveAddressRequest, opts ...grpc.CallOption) (*DeleteUserReceiveAddressResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteUserReceiveAddress(ctx, in, opts...)
}

func (m *defaultUser) GetUserReceiveAddressList(ctx context.Context, in *GetUserReceiveAddressListRequest, opts ...grpc.CallOption) (*GetUserReceiveAddressListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserReceiveAddressList(ctx, in, opts...)
}

func (m *defaultUser) AddUserCollection(ctx context.Context, in *AddUserCollectionRequest, opts ...grpc.CallOption) (*AddUserCollectionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddUserCollection(ctx, in, opts...)
}

func (m *defaultUser) DeleteUserCollection(ctx context.Context, in *DeleteUserCollectionRequest, opts ...grpc.CallOption) (*DeleteUserCollectionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteUserCollection(ctx, in, opts...)
}

func (m *defaultUser) GetUserCollectionList(ctx context.Context, in *GetUserCollectionListRequest, opts ...grpc.CallOption) (*GetUserCollectionListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserCollectionList(ctx, in, opts...)
}

func (m *defaultUser) GetUserReceiveAddressInfo(ctx context.Context, in *GetUserReceiveAddressInfoRequest, opts ...grpc.CallOption) (*UserReceiveAddress, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserReceiveAddressInfo(ctx, in, opts...)
}
