// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: product.proto

package productclient

import (
	"context"

	"github.com/fyerfyer/go-zero-ecommerce/ecommerce/product/rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProductRequest  = product.GetProductRequest
	GetProductResponse = product.GetProductResponse
	ProductItem        = product.ProductItem

	Product interface {
		GetProducts(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) GetProducts(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProducts(ctx, in, opts...)
}
