// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shippingFieldNames          = builder.RawFieldNames(&Shipping{}, true)
	shippingRows                = strings.Join(shippingFieldNames, ",")
	shippingRowsExpectAutoSet   = strings.Join(stringx.Remove(shippingFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	shippingRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(shippingFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	shippingModel interface {
		Insert(ctx context.Context, data *Shipping) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Shipping, error)
		Update(ctx context.Context, data *Shipping) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShippingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Shipping struct {
		Id               int64     `db:"id"`
		Orderid          string    `db:"orderid"`
		Userid           int64     `db:"userid"`
		ReceiverName     string    `db:"receiver_name"`
		ReceiverPhone    string    `db:"receiver_phone"`
		ReceiverMobile   string    `db:"receiver_mobile"`
		ReceiverProvince string    `db:"receiver_province"`
		ReceiverCity     string    `db:"receiver_city"`
		ReceiverDistrict string    `db:"receiver_district"`
		ReceiverAddress  string    `db:"receiver_address"`
		CreateTime       time.Time `db:"create_time"`
		UpdateTime       time.Time `db:"update_time"`
	}
)

func newShippingModel(conn sqlx.SqlConn) *defaultShippingModel {
	return &defaultShippingModel{
		conn:  conn,
		table: `"public"."shipping"`,
	}
}

func (m *defaultShippingModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShippingModel) FindOne(ctx context.Context, id int64) (*Shipping, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", shippingRows, m.table)
	var resp Shipping
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShippingModel) Insert(ctx context.Context, data *Shipping) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, shippingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Orderid, data.Userid, data.ReceiverName, data.ReceiverPhone, data.ReceiverMobile, data.ReceiverProvince, data.ReceiverCity, data.ReceiverDistrict, data.ReceiverAddress)
	return ret, err
}

func (m *defaultShippingModel) Update(ctx context.Context, data *Shipping) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, shippingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Orderid, data.Userid, data.ReceiverName, data.ReceiverPhone, data.ReceiverMobile, data.ReceiverProvince, data.ReceiverCity, data.ReceiverDistrict, data.ReceiverAddress)
	return err
}

func (m *defaultShippingModel) tableName() string {
	return m.table
}
